config/routes.rb
Rails.application.routes.draw do

  resources :crime_reports
  root to: 'crime_reports#new'
  get '/stub_json/crime_committed'

end

app/models/crime_report.rb
class CrimeReport < ActiveRecord::Base

  def self.check_crime(latitude, longitude, result)
    crime_events = []
    result.values_at("features").first.each do |obj|
      crime_x = obj.values_at("geometry").first.values_at("x").first.to_f.round(4)
      crime_y = obj.values_at("geometry").first.values_at("y").first.to_f.round(4)
      puts crime_x
      puts crime_y

      if crime_y.between?((latitude - 0.004), (latitude + 0.004)) && crime_x.between?((longitude - 0.004), (longitude + 0.004))
        puts "warning!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
         crime_events << obj
        puts crime_events
          puts "lat #{latitude} = #{crime_y}"
          puts "long #{longitude} = #{crime_x}"
        puts crime_events
      else

        puts "poop"
      end
    end
    crime_events

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/crime_reports_controller.rb
require 'twilio-ruby'

class CrimeReportsController < ApplicationController
  before_action :set_crime_report, only: [:show, :edit, :update, :destroy]
  require 'open-uri'
  require 'json'




  # GET /crime_reports
  # GET /crime_reports.json
  def index
    @crime_reports = CrimeReport.all
  end

  # GET /crime_reports/1
  # GET /crime_reports/1.json
  def show

    @address = CrimeReport.find(params[:id])
    geo_query = Geokit::Geocoders::GoogleGeocoder.geocode "#{@address.address}, Philadelphia, PA" #need to be able to pull in address
    latitude = geo_query.ll.split(',')[0].to_f.round(4)
    longitude = geo_query.ll.split(',')[1].to_f.round(4)
    @lat = geo_query.ll.split(',')[0].to_f.round(4)
    @long = geo_query.ll.split(',')[1].to_f.round(4)
    # base = "http://crimeapitest.azurewebsites.net/api/crime"
    # uri = URI.parse "#{base}?date=11-14-2014&returnCount=1000&useComcastAddress=false"
    base = "http://gis.phila.gov/ArcGIS/rest/services/PhilaGov/Police_Incidents/MapServer/0/query"
    uri = URI.parse "#{base}?where=+DISPATCH_DATE%3D'2014-11-14'&text=&objectIds=&time=&geometry=&geometryType=esriGeometryPoint&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=*&returnGeometry=true&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&f=pjson"
    response = open(uri).read
    result = JSON.parse(response)
    @crimes = CrimeReport.check_crime(latitude, longitude, result)
    @crimes_serialize = @crimes.to_json
    @body = ""
    @crimes.each do |crime|
      if @body.length < 800
      @body = @body + "#{crime.values_at('attributes').first.values_at('TEXT_GENERAL_CODE').first}
                       #{crime.values_at('attributes').first.values_at('DISPATCH_TIME').first}
                       #{crime.values_at('attributes').first.values_at('LOCATION_BLOCK').first}"
      end
         # "#{crime.values_at('attributes').first.values_at('TEXT_GENERAL_CODE').first}

         #  #{crime.values_at('attributes').first.values_at('DISPATCH_TIME').first}

         #  #{crime.values_at('attributes').first.values_at('LOCATION_BLOCK').first}  "
    end
    # puts @body
    # put your own credentials here
       #  set up a client to talk to the Twilio REST API
    if @body != ""
        @client = Twilio::REST::Client.new(ENV["TWILIO_ACCOUNT_SID"], ENV["TWILIO_AUTH_TOKEN"])

           @client.messages.create(
              from: '+12672457083',
              to: "+1#{@address.phonenumber}",
              body: "#{@body}",
        )
    end
  end

  # GET /crime_reports/new
  def new
    @crime_report = CrimeReport.new
  end

  # POST /crime_reports
  # POST /crime_reports.json
  def create
    @crime_report = CrimeReport.create(:address => params[:crime_report][:address], :phonenumber  => params[:crime_report][:phonenumber])

    if @crime_report.save
      redirect_to @crime_report
    else
      format.html { render :new }
      format.json { render json: @place.errors, status: :unprocessable_entity }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crime_report
      @crime_report = CrimeReport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crime_report_params
      params[:crime_report]
    end
end

app/controllers/stub_json_controller.rb
class StubJsonController < ApplicationController
  def crime_committed
    puts 'hello'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crime_reports_helper.rb
module CrimeReportsHelper
end

app/helpers/stub_json_helper.rb
module StubJsonHelper
end

app/views/crime_reports/_form.html.erb
<%= form_for(@crime_report) do |f| %>
  <% if @crimes.length == 0 %>
    <div class="info-success" style="color: green; border: 5px solid green; width: 450px;">
      <h2>No crimes in area. Check Completed</h2>
      <ul>
        <% @crime_report.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% else %>
    <div id="error_explanation">
      <h2>There have been crimes in your area. We recommend locking and arming your system today.</h2>

        <% @crimes.each do |crime| %>
          <%= crime.values_at("attributes").first.values_at("TEXT_GENERAL_CODE").first %>
          committed at:
          <%= crime.values_at("attributes").first.values_at("DISPATCH_TIME").first %>
          In the
          <%= crime.values_at("attributes").first.values_at("LOCATION_BLOCK").first %>
          <br>
          <br>
        <% end %>

      <ul>
        <% @crime_report.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>

  <% end %>

  <div id="map-canvas"></div>

<% end %>

app/views/crime_reports/edit.html.erb
<h1>Editing crime_report</h1>
<%= render 'form' %>
<%= link_to 'Show', @crime_report %> |
<%= link_to 'Back', crime_reports_path %>

app/views/crime_reports/index.html.erb
<h1>Listing crime_reports</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @crime_reports.each do |crime_report| %>
      <tr>
        <td><%= link_to 'Show', crime_report %></td>
        <td><%= link_to 'Edit', edit_crime_report_path(crime_report) %></td>
        <td><%= link_to 'Destroy', crime_report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Crime report', new_crime_report_path %>

app/views/crime_reports/new.html.erb
<h1 id='create_title'>Create Crime Report</h1>
<div class="row">
<div class='col-md-6'>
<%= form_for @crime_report, class: 'col-md-6', id: 'crime-form' do |f| %>
<div class = "form-group">
  <%= f.label :address %>:
  <%= f.text_field :address, placeholder: "# Street name", class: 'form-control address-label' %><br />
</div>
<div class = "form-group">
  <%= f.label :phonenumber %>:
  <%= f.text_field :phonenumber, placeholder: "# Phone Number", class: 'form-control address-label' %><br />
</div>
<div class="actions">
  <%= f.submit "Check for Crime", class: 'btn btn-success' %>
</div>
<% end %>
</div>

<div class='col-md-6'>
<img src="http://www.thedrinksbusiness.com/wordpress/wp-content/uploads/archive/images/stories/FWOT_pics/05_26_2011/burglar.jpg" style = "hieght:100%; width:100%; align:center"/>
</div>
</div>

app/views/crime_reports/show.html.erb
<p id="notice"><%= notice %></p>
<div id="crime-container" class="row">
<div class="col-md-offset-4">
<h1>New crime report</h1>
</br>


<%= @address.address %>, Philadelphia PA
<br>
Geo Co-ords: <%= @lat %>, <%= @long %>

<%= render 'form' %>
</div>
</div>
<br>
<%= link_to 'Back', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrystalBal</title>
  <script type="text/javascript" src='/assets/Index.js'></script>
 <script type="text/javascript"
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBw6CG5Msl6Pce7mSKItcjwuPjThByVZao">
    </script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <script>
    var crimes = {
      center: {
          "x": <%= @long %>,
          "y": <%= @lat %>
      },
      points:
           <%= raw @crimes_serialize %>

    }




     var map = new crimemap(crimes);

        google.maps.event.addDomListener(window, 'load', map.initialize);
  </script>
   <style type="text/css">
        #map-canvas {
            height: 100%;
            margin: 0;
            padding: 0;
            width: 600px;
            height:500px;

            border: 1px solid #000;
        }
    </style>


</head>
<body>
<%= yield %>

</body>
</html>

app/views/stub_json/crime_committed.html.erb
<html>
<head><!-- link rel="alternate stylesheet" type="text/css" href="resource://gre-resources/plaintext.css" title="Wrap Long Lines"> --></head>
<body>
  <pre>
   "displayFieldName" : "DC_DIST",
                "fieldAliases" : {
                  "DC_DIST" : "DC_DIST",
                  "SECTOR" : "SECTOR",
                  "DISPATCH_DATE_TIME" : "DISPATCH_DATE_TIME",
                  "DISPATCH_DATE" : "DISPATCH_DATE",
                  "DISPATCH_TIME" : "DISPATCH_TIME",
                  "HOUR" : "HOUR",
                  "DC_KEY" : "DC_KEY",
                  "LOCATION_BLOCK" : "LOCATION_BLOCK",
                  "UCR_GENERAL" : "UCR_GENERAL",
                  "OBJECTID" : "OBJECTID",
                  "TEXT_GENERAL_CODE" : "TEXT_GENERAL_CODE",
                  "POINT_X" : "POINT_X",
                  "POINT_Y" : "POINT_Y"
                },
                "geometryType" : "esriGeometryPoint",
                "spatialReference" : {
                  "wkid" : 4269
                },
                "fields" : [
                  {
                    "name" : "DC_DIST",
                    "type" : "esriFieldTypeString",
                    "alias" : "DC_DIST",
                    "length" : 2
                  },
                  {
                    "name" : "SECTOR",
                    "type" : "esriFieldTypeString",
                    "alias" : "SECTOR",
                    "length" : 1
                  },
                  {
                    "name" : "DISPATCH_DATE_TIME",
                    "type" : "esriFieldTypeDate",
                    "alias" : "DISPATCH_DATE_TIME",
                    "length" : 36
                  },
                  {
                    "name" : "DISPATCH_DATE",
                    "type" : "esriFieldTypeString",
                    "alias" : "DISPATCH_DATE",
                    "length" : 30
                  },
                  {
                    "name" : "DISPATCH_TIME",
                    "type" : "esriFieldTypeString",
                    "alias" : "DISPATCH_TIME",
                    "length" : 30
                  },
                  {
                    "name" : "HOUR",
                    "type" : "esriFieldTypeSmallInteger",
                    "alias" : "HOUR"
                  },
                  {
                    "name" : "DC_KEY",
                    "type" : "esriFieldTypeString",
                    "alias" : "DC_KEY",
                    "length" : 12
                  },
                  {
                    "name" : "LOCATION_BLOCK",
                    "type" : "esriFieldTypeString",
                    "alias" : "LOCATION_BLOCK",
                    "length" : 45
                  },
                  {
                    "name" : "UCR_GENERAL",
                    "type" : "esriFieldTypeString",
                    "alias" : "UCR_GENERAL",
                    "length" : 50
                  },
                  {
                    "name" : "OBJECTID",
                    "type" : "esriFieldTypeOID",
                    "alias" : "OBJECTID"
                  },
                  {
                    "name" : "TEXT_GENERAL_CODE",
                    "type" : "esriFieldTypeString",
                    "alias" : "TEXT_GENERAL_CODE",
                    "length" : 255
                  },
                  {
                    "name" : "POINT_X",
                    "type" : "esriFieldTypeDouble",
                    "alias" : "POINT_X"
                  },
                  {
                    "name" : "POINT_Y",
                    "type" : "esriFieldTypeDouble",
                    "alias" : "POINT_Y"
                  }
                ],
                "features" : [
                  {
                    "attributes" : {
                      "DC_DIST" : "15",
                      "SECTOR" : "3",
                      "DISPATCH_DATE_TIME" : 1355940000000,
                      "DISPATCH_DATE" : "2012-12-19",
                      "DISPATCH_TIME" : "18:00:00",
                      "HOUR" : 18,
                      "DC_KEY" : "201215122134",
                      "LOCATION_BLOCK" : "6800 BLOCK TULIP ST",
                      "UCR_GENERAL" : "500",
                      "OBJECTID" : 532,
                      "TEXT_GENERAL_CODE" : "Burglary Residential",
                      "POINT_X" : -75.042410129999993,
                      "POINT_Y" : 40.02350569
                    },
                    "geometry" : {
                      "x" : -75.042410134000022,
                      "y" : 40.023505689999979
                    }
                  },

                  ...

                    "attributes" : {
                      "DC_DIST" : "03",
                      "SECTOR" : "3",
                      "DISPATCH_DATE_TIME" : 1356958140000,
                      "DISPATCH_DATE" : "2012-12-31",
                      "DISPATCH_TIME" : "12:49:00",
                      "HOUR" : 12,
                      "DC_KEY" : "201203082580",
                      "LOCATION_BLOCK" : "2400 BLOCK S SARTAIN ST",
                      "UCR_GENERAL" : "500",
                      "OBJECTID" : 595642,
                      "TEXT_GENERAL_CODE" : "Burglary Residential",
                      "POINT_X" : -75.166264720000001,
                      "POINT_Y" : 39.919841759999997
                    },
                    "geometry" : {
                      "x" : -75.166264715000011,
                      "y" : 39.919841763000022
                    }
                  }
                ]
              }
  </pre>
</body>
</html>